name: CI for Main Branch

on:
  push:
    branches:
      - main

jobs:
  prebuild:
    name: Prebuild Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x64]
        node: [18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x]
        exclude:
          - os: windows-latest
            node: 23.x
    timeout-minutes: 30
    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Setup Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev linux-libc-dev
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v5
      - run: npm i
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip --arch ${{ matrix.arch }} -u ${{ secrets.PREBUILD_TOKEN }}
